tasty_bytes:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: DBT_POC
      database: DBT_POC
      schema: dev
      warehouse: DBT_POC
      threads: 8
    prod:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: DBT_POC
      database: DBT_POC
      schema: prod
      warehouse: DBT_POC
      threads: 8
