name: PR Accepted Deployment

run-name: PR from ${{ github.actor }} accepted

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  run-snowflake-dbt-job:
    name: Run on Accepted PR
    runs-on: ubuntu-latest

    environment: prod

    env:
      SNOWFLAKE_CLI_FEATURES_ENABLE_DBT: true
      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_DATABASE: DBT_POC
      SNOWFLAKE_SCHEMA: DBO
      SNOWFLAKE_ROLE: DBT_POC
      SNOWFLAKE_WAREHOUSE: DBT_POC

    steps:

      - name: Main Branch Deployment Audit
        run: |
          echo "===================================================="
          echo "MAIN BRANCH DEPLOYMENT"
          echo "===================================================="
          echo "Triggered By    : ${{ github.actor }}"
          echo "Repository      : ${{ github.repository }}"
          echo "Branch          : ${{ github.ref_name }}"
          echo "Commit SHA      : ${{ github.sha }}"
          echo "Workflow Run ID : ${{ github.run_id }}"
          echo "===================================================="

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install Snowflake CLI
        uses: snowflakedb/snowflake-cli-action@v2.0
        with:
          use-oidc: true

      - name: Check Snowflake CLI Version
        run: snow --version

      - name: Snowflake Connection Test
        run: snow connection test -x

      - name: Deploy Production DBT Project
        run: |
          snow dbt deploy tasty_bytes_dbt_object_gh_action \
          --source ./tasty_bytes_dbt_demo \
          --default-target prod \
          --dbt-version 1.10.15 \
          --force -x

      - name: List DBT Projects
        run: snow dbt list -x

      - name: Deployment Success
        if: success()
        run: |
          echo "===================================================="
          echo "DEPLOYMENT STATUS : SUCCESS"
          echo "Environment       : PROD"
          echo "Commit SHA        : ${{ github.sha }}"
          echo "===================================================="

      - name: Deployment Failure
        if: failure()
        run: |
          echo "===================================================="
          echo "DEPLOYMENT STATUS : FAILED"
          echo "Environment       : PROD"
          echo "Commit SHA        : ${{ github.sha }}"
          echo "Review previous step logs for exact error"
          echo "===================================================="